// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY']!,
    appId: '1:755558265763:web:182b32a3766b585a842016',
    messagingSenderId: '755558265763',
    projectId: 'ledgerattend',
    authDomain: 'ledgerattend.firebaseapp.com',
    storageBucket: 'ledgerattend.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY']!,
    appId: '1:755558265763:android:98eba1b768cf8ea4842016',
    messagingSenderId: '755558265763',
    projectId: 'ledgerattend',
    storageBucket: 'ledgerattend.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY']!,
    appId: '1:755558265763:ios:cf7ceece6bbea5af842016',
    messagingSenderId: '755558265763',
    projectId: 'ledgerattend',
    storageBucket: 'ledgerattend.firebasestorage.app',
    iosBundleId: 'com.example.ledgerAttend',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY']!,
    appId: '1:755558265763:ios:cf7ceece6bbea5af842016',
    messagingSenderId: '755558265763',
    projectId: 'ledgerattend',
    storageBucket: 'ledgerattend.firebasestorage.app',
    iosBundleId: 'com.example.ledgerAttend',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WINDOWS_API_KEY']!,
    appId: '1:755558265763:web:7fef0b4996e3457f842016',
    messagingSenderId: '755558265763',
    projectId: 'ledgerattend',
    authDomain: 'ledgerattend.firebaseapp.com',
    storageBucket: 'ledgerattend.firebasestorage.app',
  );
}
